### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by michmattera** [michmattera/heart-disease-analysis-and-prediction#4]
Data cleaning step 

## Tasks

- [ ] Check for missing values
- [ ] Check for unbalance target
- [ ] Check for unbalanced variables
- [ ] Spilt data into train and test set
- [ ] Save clean data
