### ISSUE TITLE
Feature engineering notebook

### ISSUE THREAD

**Issue by michmattera** [michmattera/heart-disease-analysis-and-prediction#5]
Creating new notebook for feature engineering step

## Tasks

- [x] Create new notebook
- [x] Load data cleaned
- [x] Find best transformers for all variables
- [x] Apply transformers
