### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by michmattera** [michmattera/heart-disease-analysis-and-prediction#7]
Description:
- Create and organize different pages with streamlit,.

## Tasks

- [x] Start creating dashboard
- [x] Create and finish page 1
- [x] Create and finish page 2
- [x] Create and finish page 3
- [x] Create and finish page 4
- [x] Create and finish page 5
